server:
  port: 9000
spring:
  application:
    name: zuul-service

eureka:
  client:
    register-with-eureka: true #是否注册到Eureka服务中
    fetch-registry: true #是否从Eureka服务中获取注册信息
    service-url: #Eureka客户端与服务端进行交互的地址
      defaultZone: http://ppepper:123456@127.0.0.1:7000/eureka/
  instance:
    prefer-ip-address: true #把ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
zuul:
  sensitive-headers:  # 设置敏感参数 cookie,set-Cookie,authorization
  routes:
   goods-service:
         path: /api/goods/**
         serviceId: goods-service
         strip-prefix: false
   order-service:
         path: /api/order/**
         serviceId: order-service
         strip-prefix: false
   coupon-service:
         path: /api/coupon/**
         serviceId: coupon-service
         strip-prefix: false
   sso-service:
         path: /api/sso/**
         serviceId: sso-service
         strip-prefix: false
   sso-service:
         path: /api/account/**
         serviceId: account-service
         strip-prefix: false
