server:
  port: 8000
spring:
  application:
    name: goods-service #指定服务名称
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/b2c-mall?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 1234
    maxActive: 30
    minIdle: 5
    maxWait: 10000
    validationQuery: "SELECT X"
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    register-with-eureka: true #是否注册到Eureka服务中
    fetch-registry: false #是否从Eureka服务中获取注册信息
    service-url:  #Eureka客户端与服务端进行交互的地址
     defaultZone: http://ppepper:123456@127.0.0.1:7000/eureka/
  instance:
    prefer-ip-address: true #把ip地址注册到Eureka服务中

